include("${CMAKE_CURRENT_LIST_DIR}/watcom-base.cmake")

set(CMAKE_SYSTEM_NAME "DOS")
set(CMAKE_SYSTEM_PROCESSOR "x86")

find_program(CMAKE_C_COMPILER NAMES wcl386 PATHS "${WATCOM_BIN_DIR}")
find_program(CMAKE_CXX_COMPILER NAMES wcl386 PATHS "${WATCOM_BIN_DIR}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "")

list(APPEND CMAKE_INCLUDE_PATH "${WATCOM_ROOT}/h")
list(APPEND CMAKE_LIBRARY_PATH "${WATCOM_ROOT}/lib386")
